### ISSUE TITLE
show_attributes default setting not according documentation

### ISSUE THREAD

**Issue by Earthweb-EWS** [mlamberts78/weather-chart-card#9] opened 2023-07-27 18:32 UTC
In documentation is the show_attributes setting described as default=true, but in version 1.6.3 the setting is default=false.
Not a big problem, but maybe you can have a look at it :-)

**Comment by mlamberts78** [comment] 2023-07-27 18:41
I cannot reproduce the issue, is show_attributes on false when you create a new card?

**Comment by Earthweb-EWS** [comment] 2023-07-27 18:45
this is my config, without explicit define this setting, the values aren't showing in the card:

`    - type: custom:weather-chart-card
      entity: weather.buienradar
      temp: sensor.esp_weatherstation_sht3x_temperature
      humid: sensor.esp_weatherstation_sht3x_humidity
      show_main: true
      show_attributes: true
      forecast:
        labels_font_size: 16
      units:
        speed: Bft`

**Comment by mlamberts78** [comment] 2023-07-27 19:16
Thanks for the clarification, I found the issue and the fix will be included in the next release.

**Closed** 2023-07-28 13:46 UTC
Labels: bug
