### ISSUE TITLE
Does not display on Android tablet

### ISSUE THREAD

**Issue by fugazzy** [mlamberts78/weather-chart-card#51] opened 2023-11-18 15:55 UTC
Hello I do experience a strange issue:
On my wall android 11 poe wall tablet (Allnet) the card is not shown: „custom element doesn’t exist“.
(FK Browser and HomeAssistant App)
On all other systems, Mac, iPhone, iPad the same view is rendered fine: Safari, Chrome, HA App.
Any ideas on this?

**Comment by mlamberts78** [comment] 2023-11-19 17:30
Did you already try to clear the cache on your android device for the home assistant app?

**Comment by fugazzy** [comment] 2023-11-19 22:32
Yes I even tried reinstalling fully kiosk browser and homeassistant app - it helps nothing. 
Now I tried chrome and here it works fine, but its not what I need.
I have no idea why only this card does not work on just this device.

**Comment by fugazzy** [comment] 2023-11-25 12:44
Kann diese Meldung die Ursache sein?
`42:58.187 -- [ERROR] Uncaught SyntaxError: Unexpected token '=' -- on line 615 of http://192.168.1.129:8123/hacsfiles/weather-chart-card/weather-chart-card.js?hacstag=[665501829221](tel:665501829221)`

**Comment by fugazzy** [comment] 2023-11-29 10:01
Any news on this issue?

**Comment by emopm1** [comment] 2024-02-05 16:20
I'm having a similar issue. This card works fine if I use the Home Assistant app and if I browse Home Assistant using chrome or safari browsers, but it shows the "custom element doesn’t exist" only when I browse Home Assistant from my Samsung Family Hub fridge browser.

Any update with this issue?

**Comment by user86000** [comment] 2024-02-06 20:12
on Windows 11 same issue
google chrome i.o.
microsoft edge: custom element does not exist: wether-chart-card

**Comment by mlamberts78** [comment] 2024-02-07 13:41
I'm able to reproduce this issue on my Samsung Family Hub fridge browser, but till now I didn't find a solution.
It is not only related to my card, it is an issue with a lot of custom cards installed via HACS, that is what I see on https://community.home-assistant.io/ and also on my Samsung Family Hub fridge browser I have multiple cards showing the same error. (e.g. LG Remote and Sonos card).

**Comment by Arturasm** [comment] 2024-02-09 04:52
Same error in Safari on iPhone, Edge on Iphone. All good on the Edge on PC. Very strange.

**Comment by mlamberts78** [comment] 2024-02-09 11:04
Please test version 2.2.7, the issue should be resolved in that version.

**Comment by user86000** [comment] 2024-02-09 21:50
i have found the problem
card conflicts with sunsynk powerflowcard and maybe with other powerflowcards
only last installed card works

if i delete sunsynk card  the weather flowcard works otherwise card not found
if i install weather after sunsynk the formerly working sunsynk isn't found

creepy

**Comment by emopm1** [comment] 2024-02-09 22:48
I did the upgrade to version 2.2.7 an it fixed the issue on my Samsung Family Hub fridge browser. It is working now. Thanks for the fix.

**Comment by Arturasm** [comment] 2024-02-10 08:13
> i have found the problem card conflicts with sunsynk powerflowcard and maybe with other powerflowcards only last installed card works
> 
> if i delete sunsynk card the weather flowcard works otherwise card not found if i install weather after sunsynk the formerly working sunsynk isn't found
> 
> creepy

Confirm - sunsyk is the trouble maker if used together.  2.2.7 doesn’t solved.

**Comment by mlamberts78** [comment] 2024-02-10 08:39
> > i have found the problem card conflicts with sunsynk powerflowcard and maybe with other powerflowcards only last installed card works
> > if i delete sunsynk card the weather flowcard works otherwise card not found if i install weather after sunsynk the formerly working sunsynk isn't found
> > creepy
> 
> Confirm - sunsyk is the trouble maker if used together. 2.2.7 doesn’t solved.

Actually it seems there where two problems in this report, 2.2.7 did solve issues on older devices.
Good catch the conflict with sunsyk, that seems to be a HACS problem? There is not much I can do here.

**Closed** 2024-02-10 08:42 UTC
Labels: bug
